### ISSUE TITLE
mistake when update rubymotion to 3.14

### ISSUE THREAD

**Issue by h1u2i3** [darinwilson/moran#7]
rubymotion 3.14

E/cn/qxtf/hyys( 2780): Exception raised: NoMethodError: undefined method `lstrip' for #<org.json.JSONObject:0x8890001d>
E/cn/qxtf/hyys( 2780): 	from moran.rb:9 in `parse'
